language: python
python:
- '2.7'
install:
- "pip install -U pip"
- "pip install setuptools==0.8"
- "pip install setuptools_git==1.1"
- "pip install -r requirements.txt"
- "pip install -e ."
script:
- nosetests src
